### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by demurgos** [jbandela/simple_match#1]
Hi,
It seems that the documentation is a bit outdated:

```cpp
#incude "simple_match/simple_match.hpp"
#incude "simple_match/some_none.hpp"
```

Should be

```cpp
#incude "simple_match/simple_match.hpp"
```

And `tup` seems to have been renamed to `ds` ?

**Comment by jbandela** [comment]
Thanks for the comment. You are correct. If you would submit a pull request, I would accept it, or else I will eventually overhaul the docs.

**Comment by jbandela** [comment]
Thanks for the issue. Fixed.
