### ISSUE TITLE
../include/simple_match/from_string.hpp: No such file or directory

### ISSUE THREAD

**Issue by yuriv** [jbandela/simple_match#6]
I tried to compile test.cpp and got error:

./test.cpp:12:10: fatal error: ../include/simple_match/from_string.hpp: No such file or directory
 #include "../include/simple_match/from_string.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The file really absent.

**Comment by jbandela** [comment]
Thanks for the feedback. Should be fixed now. test.cpp was using obsolete functions.
